# Generated by Django 5.0.6 on 2024-07-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_socialpost_id_hashtags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtags',
            old_name='name',
            new_name='hashtag_name',
        ),
        migrations.RemoveField(
            model_name='hashtags',
            name='posts',
        ),
        migrations.AddField(
            model_name='hashtags',
            name='post',
            field=models.ManyToManyField(related_name='hashtag', to='posts.socialpost'),
        ),
        migrations.AlterModelTable(
            name='hashtags',
            table='hashtag',
        ),
    ]
